Added UI, Shared Preferences, TDD File structure, User Model
ECellNitrr/teesco-app pull request #15
Opened 2020-05-05 16:28 UTC by Hard-Coder05

### Fixes #ISSUE_NUMBER

### Description

Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

**Type of Change:** (Delete irrelevant options)
- Code
- Testing
- User Interface
- Documentation

**Code/Quality Assurance Only** (Delete irrelevant options)

- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:

- [ *] My PR follows the style guidelines of this project
- [ *] I have performed a self-review of my own code or materials
- [ *] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ *] Any dependent changes have been merged

**Code/Quality Assurance**
- [ *] My code follows TDD clean architecture
- [ ] My changes generate no new warnings 
- [ *] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-05-06 20:12 UTC, werainkhatri commented
please check how others have raised PRs and edit.

2020-05-07 04:57 UTC, Hard-Coder05 commented
PR has been edited! Kindly check this out.

2020-05-07 10:26 UTC, werainkhatri requested changes
Create the domain layer. Add all the entities according to the functions like
i. functions for password and username validations. The presentation layer should never contain business logic. add all the logic in usecases of domain layer.
i. function for login post api. an entity for login_profile (created already). make a function to call the api and an entity to handle response
In Clean TDD world, models -> entities and functions -> usecases

2020-05-07 10:26 UTC, werainkhatri commented on lib/features/Auth/login/data/datasources/shared_prefs.dart
> +final String key_Email="email";
Name non-constant identifiers using lowerCamelCase
```suggestion
final String keyEmail = "email";
```

2020-05-07 10:26 UTC, werainkhatri commented on lib/features/Auth/login/data/datasources/shared_prefs.dart
> +final String key_Email="email";
use `static const` instead of `final`
```suggestion
static const String keyEmail = "email";
```

2020-05-07 10:26 UTC, werainkhatri commented on lib/features/Auth/login/data/datasources/shared_prefs.dart
> +  Future<bool> set_Email(String email) async{
Name non-constant identifiers using lowerCamelCase
```suggestion
  Future<bool> setEmail(String email) async {
```

2020-05-07 10:26 UTC, werainkhatri commented on lib/features/Auth/login/data/datasources/shared_prefs.dart
> +class Constant{
there is a strings.dart file in core/res/
make sure you add all constant strings in there

2020-05-07 10:26 UTC, werainkhatri commented on lib/features/Auth/login/data/datasources/shared_prefs.dart
> +    _email=prefs.getString(Constant().key_Email)??null;
Read a little about the `??` operator
You have used it wrong

2020-05-07 10:26 UTC, werainkhatri commented on lib/features/Auth/login/presentation/pages/LoginScreen.dart
> +
file names should be **lowercase words divided by underscores**
..../pages/login_screen.dart

2020-05-07 10:26 UTC, werainkhatri commented on lib/features/home/HomeScreen.dart
> +import 'package:flutter/material.dart';
file name
home_screen.dart

2020-05-07 10:26 UTC, werainkhatri commented on lib/features/home/HomeScreen.dart
> +class HomeScreen extends StatefulWidget {
This feature is not requested in the issue
don't create files/features not explicitly asked for in the issue
don't overengineer

2020-05-07 10:26 UTC, werainkhatri commented on pubspec.yaml
> +  toast:
this plugin is better
also mention the current version always!
use `Pubspec Assist` extension in vscode to easily add packages
```suggestion
  fluttertoast: ^4.0.1
```

2020-05-07 10:26 UTC, werainkhatri commented on lib/main.dart
>  class MyApp extends StatelessWidget {
try not to alter files not asked for in the issue

2020-05-07 10:26 UTC, werainkhatri commented on lib/features/Auth/login/data/models/user.dart
> +class Login {
if its a user file
name the class User
```suggestion
class User {
```
or name the file login_profile.dart
and
```suggestion
class LoginProfile {
```
keep specific file names

2020-05-07 15:31 UTC, werainkhatri commented on lib/features/Auth/login/data/datasources/shared_prefs.dart
> +    _email=prefs.getString(Constant().key_Email)??null;
read about them?

2020-05-07 15:32 UTC, werainkhatri commented on lib/features/Auth/login/presentation/pages/LoginScreen.dart
> +
also change the feature name to **auth**.

2020-05-07 15:35 UTC, werainkhatri reviewed
domain layer explained in the last comment still remaining

2020-05-08 06:25 UTC, Hard-Coder05 commented on lib/features/Auth/login/presentation/pages/LoginScreen.dart
> +
done sie

2020-05-08 06:27 UTC, Hard-Coder05 commented on lib/features/Auth/login/data/datasources/shared_prefs.dart
> +    _email=prefs.getString(Constant().key_Email)??null;
will read and do necessary changes

2020-05-22 15:58 UTC, closed without merging