UI - Organisation Creation Page
ECellNitrr/teesco-app pull request #29
Opened 2020-05-28 18:34 UTC by Hard-Coder05

### Fixes #28 

### Description

The basic UI of the page where organisation will add their name, logo and tagline has been created.

**Type of Change:** 
- Code
- User Interface

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

It has been tested on my local device.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

**Code/Quality Assurance**
- [ ] My code follows TDD clean architecture
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

**ScreenShot of page created by me**
![Screenshot_2020-05-28-23-39-22-039_com example teesco](https://user-images.githubusercontent.com/54059881/83179615-dbbf9980-a13f-11ea-8485-cf4a6796677e.jpg)

2020-05-28 18:46 UTC, Hard-Coder05 commented
Reviewers: @naveennvrgup @werainkhatri @thepseudoartist

2020-05-29 08:26 UTC, werainkhatri commented
> Reviewers: @naveennvrgup @werainkhatri @thepseudoartist

don't add reviewers in comments...
there is a section on the top right hand side called reviewers. Request review from there.

2020-05-29 08:50 UTC, werainkhatri requested changes
A general request:
make a habbit of using **reformating** while writing code
`ctrl+shift+I` for vscode and `ctrl+shift+L` for android studio (not sure, check it)
This will help in indentation and overall good code.

Also, i'm going to use emotes to display importance of a review
laugh: not very important.
eyes: fairly important
-1 (thumbs down) : very important!

2020-05-29 08:50 UTC, werainkhatri commented on lib/screens/organisation_registration/organisation_registration.dart
> +class AddOrganisation extends StatefulWidget {
1. Make sure the name of a widget ends with what it actually is.
```suggestion
class AddOrganisationScreen extends StatefulWidget {
```
2. Make sure the name of the file and name of widget in it is related
```suggestion
class OrganisationRegistrationScreen extends StatefulWidget {
```

2020-05-29 08:50 UTC, werainkhatri commented on lib/screens/organisation_registration/organisation_registration.dart
> +          leading: GestureDetector(
Instead of GestureDetector, use IconButton
applies to all places where the child of a GestureDetector is an Icon

2020-05-29 08:50 UTC, werainkhatri commented on lib/screens/organisation_registration/organisation_registration.dart
> +          title: Text("TEESCO",style: TextStyle(color: Colors.black),),
The title text can be **Organisation Registration**

2020-05-29 08:50 UTC, werainkhatri commented on lib/screens/organisation_registration/widgets/name_field.dart
> +    return Container(
no need for a container here

2020-05-29 08:50 UTC, werainkhatri commented on lib/screens/organisation_registration/widgets/tagline_field.dart
> +    return Container(
no need for a container here

2020-05-29 08:50 UTC, werainkhatri commented on pubspec.yaml
> +  # Upload Image
Add good comments
image_picker is a package to pick an image from gallery or click from camera
its not for uploading image
refer the usual one-liner on [pub.dev](https://pub.dev) for better plugin doc

2020-05-29 11:35 UTC, werainkhatri commented
And also, your branch is dev...
make sure you create a new branch everytime you raise a pr for an issue

2020-05-29 12:51 UTC, Hard-Coder05 commented
> And also, your branch is dev...
> make sure you create a new branch everytime you raise a pr for an issue

Yes Sir!
Will do it from the next time onwards

2020-05-29 13:09 UTC, werainkhatri reviewed
It looks good
one small review:
Write proper commits messages... refer [commit guide](https://https//github.com/ECellNitrr/teesco-app/wiki/Commit-Message-Structure) for instructions

2020-05-29 13:09 UTC, werainkhatri commented on lib/screens/organisation_registration/organisation_registration.dart
> +          leading: GestureDetector(
changing this to IconButton?

2020-05-29 20:10 UTC, naveennvrgup approved these changes
1. Works great test locally :clap: 
1. the icon button is a minor issue which can be mentioned while wiring the API so
1. Merging the PR

2020-05-29 20:10 UTC, merged